name: Issue Opened
run-name: Detect when `AMA` issue is opened

on:
  issues:
    types: [opened]

jobs:
  runs-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: List all Java files
      run: |
        find . -name "*.java"
